{% set name = "napari-zelda" %}
{% set version = "0.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-zelda-{{ version }}.tar.gz
  sha256: be4382e135556bc588f54a78c0a382e5498bb06a7cf0a16fd3ec9b0fb7c64689

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - datatable
    - json5
    - magicgui
    - matplotlib-base >=3.4.3
    - napari !=0.4.11
    - napari-plugin-engine >=0.1.4
    - numpy
    - pandas
    - python >={{ python_min }}
    - qtpy
    - scikit-image
    - scipy

test:
  imports:
    - napari_zelda
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-zelda
  summary: 3D Image Segmentation and Parent-Child relation plugin for microscopy image analysis in napari
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/RoccoDAnt/napari-zelda

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
